### ISSUE TITLE
使用寄存器版本跑斐波那契数列，会出现比老版本执行更慢的情况

### ISSUE THREAD

**Issue by zhaowentian** [Ourpalm/ILRuntimeU3D#12]
int value = Fib(30);
int Fib(int n)
{
        return n < 2 ? 1 : Fib(n - 1) + Fib(n - 2);
}

Android真机上大概有会0.3-0.4秒的差距

**Comment by liiir1985** [comment]
因为这种情况无法利用到任何寄存器版的优势，既无复杂计算，又因递归无法inline
